### ISSUE TITLE
Setting releasability on Crits data

### ISSUE THREAD

**Issue by Lambdanaut** [security-automation/crits-adapter#4]
@treyka 

I want to make changes so that releasability is set after the object is inboxed into CRITS. In the `lib_.crits_` module there's a `crits_inbox` function that uploads the object to CRITS. As Crits's API works right now, releasability must be set after the object is uploaded. I'd like to add a `crits_patch` function to update existing objects with a given action. 

I'm going forward with this. Any guidance is appreciated :v:

**Comment by treyka** [comment]
Resolved by 78e2edbb7ecdb9bdfa7d6963f61c2529ed0906a7
