### ISSUE TITLE
Errors when Crits or Edge are changed from "localhost" name in config.yaml

### ISSUE THREAD

**Issue by Lambdanaut** [security-automation/crits-adapter#7]
When Crits or Edge names are changed from "localhost" in config.yaml, edgy_crits.py throws an error. 

I'd like to be able to fix this myself soon.

**Comment by treyka** [comment]
What error? Does the box in question resolve dns normally via dig?

Cheers,
Trey
++----------------------------------------------------------------------------++

**Comment by Lambdanaut** [comment]
This might be a false alarm. I'm helping somebody install the adapter that is seeing this error and I personally remember seeing it months ago.

It's all in the same LAN. I was able to just test it out myself and am not seeing the problem anymore. They were able to fix the error they were seeing (Python error: No JSON object able to be decoded) by changing the name back to "localhost", but it's possible they made some other change as well and this had nothing to do with it. 

In any case. I just tried replicating and it's not happening for me, so I'll close this for now.
